<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DTT.Doctor.Presenter\DTT.Doctor.Presenter.csproj" />
    <ProjectReference Include="..\DTT.Doctor.Services\DTT.Doctor.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.10.0.20240616" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.10.0.20240616" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.10.0.20240616" />
    <PackageReference Include="ReaLTaiizor" Version="3.8.2.1" />
    <PackageReference Include="ZXing.Net" Version="0.16.9" />
    <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.6" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <NoWarn>$(NoWarn);WFO1000;WFO10001</NoWarn>
    <ApplicationIcon>DTT.ico</ApplicationIcon>
    <Product>DTT Healthcare - Doctor Desktop</Product>
    <Company>DTT Healthcare</Company>
    <Description>Phần mềm quản lý phòng khám DTT Healthcare (Bác sĩ, Lễ tân, Điều dưỡng, KTV, Dược sĩ)</Description>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="DTT.ico" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\logo_dtt_healthcare.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>